*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
*.sink.prometheusServlet.path=/metrics/master/prometheus
master.sink.prometheusServlet.path=/metrics/master/prometheus
worker.sink.prometheusServlet.path=/metrics/worker/prometheus
driver.sink.prometheusServlet.path=/metrics/executors/prometheus
executor.sink.prometheusServlet.path=/metrics/executors/prometheus